### PR TITLE
allow dynamic properties

### PR DESCRIPTION
**Pull request by venkatraj**

### CODE REVIEW

**Comment by DavidAnderson684** [comment]
@venkatraj Does the class still use dynamic properties? That's meant to have been resolved by previous issues.... have you got the master?
I'd prefer to merge a fix that names the properties, since that's what we've done with previous ones.

**Comment by venkatraj** [comment]
@DavidAnderson684 Deprecation notice is triggered by this line
https://github.com/DavidAnderson684/plugin-update-checker/blob/master/Puc/v4p13/Metadata.php#L47

This is the property
`PHP Deprecated:  Creation of dynamic property Puc_v4p13_Plugin_Info::$x-spm-subscription-active`

I don't see any property names in this PR?
https://github.com/DavidAnderson684/plugin-update-checker/pull/1

Yes, live release has this repo and has `#[AllowDynamicProperties]` in `Puc_v4p13_Plugin_Update` class

**Comment by DavidAnderson684** [comment]
@venkatraj  We should define that property, then. Since this is our private fork, there's no harm in defining the properties that our updater class uses.

**Comment by venkatraj** [comment]
@DavidAnderson684 I've ported the fix from original repo. Just curious, Is there a reason for not using V5 from original repo?

**Comment by DavidAnderson684** [comment]
@venkatraj 
> "Is there a reason for not using V5 from original repo?"
Yes, it requires PHP >= 5.6, whereas UD still supports older PHP versions than that.

**Pull request merged**
